import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Box, Button, Flex, FormControl,FormLabel, Heading ,Input,Text, Textarea } from "@chakra-ui/react";



export default function Home() {
  return (
    <>
      <Head>
        <title>Form nextJs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <Flex 
          minHeight='100vh'
          width='full'
          align='center'
          justifyContent='center'
          backgroundColor='hsl(148, 38%, 91%)'
          position='relative'
          
          >
        <Box
         px={12}
         py={12}
         width='full'
         maxWidth='450px'
         textAlign='center'
         boxShadow='lg'
         background='gray.700'
         borderRadius='6px'
        
        >
          <Heading>
            <Text textColor='gray.200' fontSize='2xl'>Registragion form</Text>
          </Heading>
          <Box>
            <form action='' autoComplete="off">

              <Flex justifyContent='space-between'>
            <FormControl isRequired marginTop='15px' width='49%'>
              <FormLabel textColor='gray.200'>First name</FormLabel>
              <Input
               type='text'
               name="name"
               border='none'
               outline='none'
               bgColor='gray.900'
               focusBorderColor="gray.600"
               color='gray.200'
               placeholder="First name"               
               />              
           </FormControl>

           <FormControl isRequired marginTop='15px' width='49%'>
              <FormLabel textColor='gray.200'>Last name</FormLabel>
              <Input
               type='text'
               name="name"
               border='none'
               outline='none'
               bgColor='gray.900'
               focusBorderColor="gray.600"
               color='gray.200'
               placeholder="Last name"               
               />               
           </FormControl>
           </Flex>

           <FormControl isRequired marginTop='15px'>
              <FormLabel textColor='gray.200'>Your e-mail</FormLabel>
              <Input
               type='text'
               name="name"
               border='none'
               outline='none'
               bgColor='gray.900'
               focusBorderColor="gray.600"
               color='gray.200'
               placeholder="Your e-mail"               
               />              
           </FormControl>

           <Flex justifyContent='space-between'>
           <FormControl isRequired marginTop='15px' width='49%'>
              <FormLabel textColor='gray.200'>Your address</FormLabel>
              <Input
               type='text'
               name="name"
               border='none'
               outline='none'
               bgColor='gray.900'
               focusBorderColor="gray.600"
               color='gray.200'
               placeholder="Your address"               
               />              
           </FormControl>

           <FormControl isRequired marginTop='15px' width='49%'>
              <FormLabel textColor='gray.200'>Your phone</FormLabel>
              <Input
               type='text'
               name="name"
               border='none'
               outline='none'
               bgColor='gray.900'
               focusBorderColor="gray.600"
               color='gray.200'
               placeholder="Your phone"               
               />               
           </FormControl>
           </Flex>

           <FormControl isRequired marginTop='15px'>
              <FormLabel textColor='gray.200'>Your descript message</FormLabel>
              <Textarea               
               name="name"
               border='none'
               outline='none'
               bgColor='gray.900'
               focusBorderColor="gray.600"
               color='gray.200'
               resize='none'
               placeholder="Your descript messag"              
               />               
           </FormControl>
              <Button
              type="submit"
              width='full'
              bgColor='green.400'
              mt={4}
              color='gray.200'
              _hover={{
                color:'black'
              }}
              >Register</Button>
              
            </form>
          </Box>
        </Box>
       </Flex>
      </main>
    </>
  );
}
